First version of site
stepancar-web-programming/2023-fall-lab-portfolio-rizoboev-a. pull request #1
Opened 2023-12-28 07:54 UTC by RizoBoy

2024-01-04 03:55 UTC, stepancar commented on contact.html
> +                                    <input type="text" class="form-control" id="email" placeholder="address@example.com">
давайте добавим валидацию для почты

2024-01-04 03:57 UTC, stepancar commented on js/Toast.min.js
> +"use strict";function Toast(t){if(!t.message)throw new Error("Toast.js - You need to set a message to display");this.options=t,this.options.type=t.type||"default",this.toastContainerEl=document.query
давайте найдем этот пакет в cdn

2024-01-04 03:59 UTC, stepancar commented on js/index.js
> +        var distance = element.getBoundingClientRect();
в коде ниже вы используете const. Пожалуйста, добейтесь консистентности в коде

2024-01-04 04:03 UTC, stepancar commented on js/index.js
> +                if ($().isInViewport(element)) {
Пока не очень понял идею. Если вы пишите именно jquery plugin то предполагается что элементы в него  передаются как это обычно делается в jquery: $(element).isInViewport(). 
Или идея в другом?

2024-01-04 04:04 UTC, stepancar commented on js/index.js
> +                        $('.members-counter').countTo({
пожалуйста, отформатируйте код перед отправкой на ревью

2024-01-04 04:07 UTC, stepancar requested changes
Оствил комментарии

2024-01-18 13:10 UTC, RizoBoy commented
@stepancar выполнил правки, проверьте пожалуйста.

2024-01-19 06:49 UTC, stepancar commented on js/index.js
> +                    const classes = element.className.split(' ');
в дом есть возможность получить классы отдельно

2024-01-19 06:50 UTC, stepancar commented on js/index.js
> +                    classes[classes.length - 1] += '-counter';
а что если этот клаасс добавлен не в конец?

2024-01-19 06:52 UTC, stepancar commented on index.html
> +                            Студент ИТМО третьего курс по направлению “Нейротехнологии и программирование”. Более 5 лет занимаюсь открытием и развитием игровых серверов в качестве полноценных прибыль
```suggestion
                            Студент ИТМО третьего курса по направлению “Нейротехнологии и программирование”. Более 5 лет занимаюсь открытием и развитием игровых серверов в качестве полноценных прибыльных проектов, благодаря чему хорошо обладаю рассудительными и организационными навыками. Создал ИИ психолога с помощью машинного обучения в качестве телеграмм бота. Всегда готов присоединиться к команде для решения задач.
```

2024-01-19 06:53 UTC, stepancar commented on index.html
> +                                <li class="nav-item">E-mail: kyles.scpsl@gmail.com</li>
Давайте сделаем ссылку таким образом чтобы при нажатии на нее открывался нативный клиент

2024-01-19 06:53 UTC, stepancar commented on index.html
> +                                <li class="nav-item">Discord: rizoboy</li>
Давайте добавим ссылку

2024-01-19 07:09 UTC, stepancar requested changes
На защиту давайте сделаем аналитику вашей страницы

2024-01-19 23:22 UTC, RizoBoy commented
@stepancar снова выполнил правки, проверьте пожалуйста.

2024-01-20 02:06 UTC, stepancar commented
@RizoBoy , new увидел код относящийся к https://github.com/stepancar-web-programming/2023-fall-lab-portfolio-rizoboev-a./pull/1#pullrequestreview-1831739043

2024-01-21 21:51 UTC, stepancar approved these changes

2024-01-21 21:52 UTC, stepancar commented
Поскольку ПР был создан почти через 1.5 месяца после дедлайна, ставлю минимальный балл.

2024-01-21 21:52 UTC, merged